=== api-evangelist/fakerapi/json-schema/fakerapi-envelope-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://fakerapi.it/schemas/envelope.json",
  "title": "Response Envelope",
  "description": "Shared response envelope returned by every FakerAPI endpoint.",
  "type": "object",
  "properties": {
    "status": { "type": "string", "description": "Always 'OK' on success.", "example": "OK" },
    "code": { "type": "integer", "description": "HTTP-style status code.", "example": 200 },
    "locale": { "type": "string", "description": "Locale used to generate the payload.", "example": "en_US" },
    "seed": { "type": ["string", "integer", "null"], "description": "Seed echoed from the request, or null.", "example": "42" },
    "total": { "type": "integer", "description": "Number of records returned in data.", "example": 10 },
    "data": { "type": "array", "description": "Generated resource collection." }
  },
  "required": ["status", "code", "locale", "total", "data"]
}

=== api-evangelist/fakerapi/examples/fakerapi-list-companies-example.json
{"status":"OK","code":200,"locale":"en_US","seed":"42","total":2,"data":[{"id":1,"name":"Brekke-Bartoletti","email":"xboehm@gmail.com","vat":"09853775915","phone":"+15743577321","country":"Somalia","addresses":[{"id":1,"street":"3026 Dorcas Drive","streetName":"Colt Forest","buildingNumber":"37572","city":"Marquardtside","zipcode":"24228-5876","country":"Somalia","country_code":"SO","latitude":84.583773,"longitude":79.919558},{"id":1,"street":"269 Hackett Crest Suite 329","streetName":"Wyman Row","buildingNumber":"432","city":"Rickyfort","zipcode":"57351-2143","country":"\u00c5land Islands","country_code":"AX","latitude":-48.101159,"longitude":-15.814804},{"id":1,"street":"12370 Carolyne Fort","streetName":"Brody Crest","buildingNumber":"160","city":"New Omari","zipcode":"47204-0177","country":"French Southern Territories","country_code":"TF","latitude":-20.625029,"longitude":-70.339042}],"website":"http:\/\/steuber.com","image":"http:\/\/placeimg.com\/640\/480\/people","contact":{"id":1,"firstname":"Ashton","lastname":"Bogan","email":"kendall.weissnat@yahoo.com","phone":"+16186959992","birthday":"1974-08-25","gender":"male","address":{"id":1,"street":"536 Desmond Heights Apt. 496","streetName":"Kihn Rest","buildingNumber":"635","city":"Bernieland","zipcode":"78082","country":"Cyprus","country_code":"CY","latitude":48.828662,"longitude":38.145593},"website":"http:\/\/hagenes.info","image":"http:\/\/placeimg.com\/640\/480\/people"}},{"id":2,"name":"Veum, Schroeder and Runolfsdottir","email":"nathaniel.klein@gmail.com","vat":"0708891314","phone":"+12485951709","country":"Croatia","addresses":[{"id":1,"street":"9966 Bode Mountain","streetName":"Autumn Square","buildingNumber":"935","city":"Marlenetown","zipcode":"22146","country":"Kazakhstan","country_code":"KZ","latitude":-5.001314,"longitude":-42.146325},{"id":1,"street":"57090 Laisha Trafficway","streetName":"VonRueden Lodge","buildingNumber":"53870","city":"South Ethyl","zipcode":"87326","country":"Christmas Island","country_code":"CX","latitude":71.237448,"longitude":49.107747}],"website":"http:\/\/quigley.com","image":"http:\/\/placeimg.com\/640\/480\/people","contact":{"id":1,"firstname":"Kristy","lastname":"Donnelly","email":"myrtle04@murazik.net","phone":"+12768316602","birthday":"1993-03-22","gender":"female","address":{"id":1,"street":"5842 Kautzer Overpass","streetName":"Beulah Expressway","buildingNumber":"43432","city":"West Howellmouth","zipcode":"08139-6733","country":"Equatorial Guinea","country_code":"GQ","latitude":35.334769,"longitude":-0.99054},"website":"http:\/\/murray.com","image":"http:\/\/placeimg.com\/640\/480\/people"}}]}

=== api-evangelist/fakerapi/examples/fakerapi-list-images-example.json
{"status":"OK","code":200,"locale":"en_US","seed":"42","total":2,"data":[{"title":"Nisi veritatis quia ut est.","description":"Ut est maxime et. Impedit sit aut illum. Facere quibusdam atque sed debitis nisi.","url":"https:\/\/picsum.photos\/640\/480"},{"title":"Et mollitia eos optio aut.","description":"Explicabo doloremque vero nulla veniam voluptas eius sint. Ratione non necessitatibus possimus ea modi omnis architecto.","url":"https:\/\/picsum.photos\/640\/480"}]}

=== api-evangelist/fakerapi/examples/fakerapi-list-texts-example.json
{"status":"OK","code":200,"locale":"en_US","seed":"42","total":2,"data":[{"title":"Mock Turtle in the.","author":"Gladyce Ortiz","genre":"Et","content":"Mock Turtle replied, counting off the fire, licking her paws and washing her face--and she is only a child!' The Queen turned crimson with fury, and, after folding his arms and frowning at the mouth."},{"title":"Knave was standing.","author":"Rae McKenzie","genre":"Illum","content":"And beat him when he finds out who was gently brushing away some dead leaves that lay far below her. 'What CAN all that green stuff be?' said Alice. 'I've so often read in the sky. Alice went on."}]}

=== api-evangelist/fakerapi/examples/fakerapi-list-persons-example.json
{"status":"OK","code":200,"locale":"en_US","seed":"42","total":2,"data":[{"id":1,"firstname":"Brown","lastname":"Schroeder","email":"emilie24@fahey.com","phone":"+18725574706","birthday":"1939-03-20","gender":"male","address":{"id":1,"street":"599 Huel Drive Suite 372","streetName":"Gladyce Bypass","buildingNumber":"6739","city":"East Trevorstad","zipcode":"25475-1707","country":"North Korea","country_code":"KP","latitude":85.275994,"longitude":-48.109736},"website":"http:\/\/jerde.com","image":"http:\/\/placeimg.com\/640\/480\/people"},{"id":2,"firstname":"Verlie","lastname":"Kerluke","email":"hblanda@romaguera.com","phone":"+16518175720","birthday":"2013-01-27","gender":"female","address":{"id":1,"street":"8553 Beatty Islands Apt. 491","streetName":"Aglae Bridge","buildingNumber":"8490","city":"New Shanieton","zipcode":"82603-0589","country":"Somalia","country_code":"SO","latitude":3.612244,"longitude":-105.141001},"website":"http:\/\/kirlin.org","image":"http:\/\/placeimg.com\/640\/480\/people"}]}

=== api-evangelist/fakerapi/examples/fakerapi-list-users-example.json
{"status":"OK","code":200,"locale":"en_US","seed":"42","total":2,"data":[{"id":1,"uuid":"23dfa992-ff16-30e9-80f4-75a1814d0efa","firstname":"Oscar","lastname":"Williamson","username":"udach","password":"Xq7OuxC\"n@=8?\"~8","email":"vernice.bartoletti@gmail.com","ip":"78.226.209.203","macAddress":"39:15:FC:EB:58:30","website":"http:\/\/cronin.biz","image":"http:\/\/placeimg.com\/640\/480\/people"},{"id":2,"uuid":"f92c5482-6f45-382c-8f52-5e9d066488db","firstname":"Eloy","lastname":"DuBuque","username":"njerde","password":"qr)tCN$[","email":"romaguera.johathan@koelpin.com","ip":"116.234.41.131","macAddress":"58:3B:0D:F1:F9:08","website":"http:\/\/volkman.net","image":"http:\/\/placeimg.com\/640\/480\/people"}]}

=== api-evangelist/fakerapi/examples/fakerapi-list-addresses-example.json
{"status":"OK","code":200,"locale":"en_US","seed":"42","total":2,"data":[{"id":1,"street":"1414 Dach Prairie Apt. 113","streetName":"Colt Forest","buildingNumber":"37572","city":"Marquardtside","zipcode":"24228-5876","country":"Mauritania","country_code":"MR","latitude":84.583773,"longitude":79.919558},{"id":2,"street":"269 Hackett Crest Suite 329","streetName":"Wyman Row","buildingNumber":"432","city":"Rickyfort","zipcode":"57351-2143","country":"\u00c5land Islands","country_code":"AX","latitude":-48.101159,"longitude":-15.814804}]}

=== api-evangelist/fakerapi/examples/fakerapi-list-products-example.json
{"status":"OK","code":200,"locale":"en_US","seed":"42","total":2,"data":[{"id":1,"name":"Et sed impedit sit aut.","description":"Nisi provident qui vero nam et aspernatur amet. Omnis inventore dolor et ut. Omnis facilis ratione totam dicta cupiditate enim. Blanditiis ratione nihil vel consequuntur voluptatem.","ean":"2369661397200","upc":"967609529178","image":"http:\/\/placeimg.com\/640\/480\/tech","images":[{"title":"Sint ratione totam occaecati.","description":"Natus ut voluptas deleniti non dolorum eum. Omnis omnis asperiores velit vero inventore hic facilis. Omnis inventore consequatur distinctio est. Ab qui commodi eum.","url":"https:\/\/picsum.photos\/640\/480"},{"title":"In ipsum quia quae nam.","description":"Et quidem similique velit voluptas earum voluptatibus voluptatibus. Nam molestias delectus asperiores rem reiciendis. Est et inventore ipsa doloremque velit veritatis facere.","url":"https:\/\/picsum.photos\/640\/480"},{"title":"Iusto vitae ipsam quia.","description":"Ut illo ipsum ut pariatur beatae sed. Sit molestiae a cumque nobis excepturi quia vero. Est deleniti explicabo praesentium id modi.","url":"https:\/\/picsum.photos\/640\/480"}],"net_price":1015069.03,"taxes":22,"price":1238384.22,"categories":[27,28,29,30,31],"tags":["laborum","dolores","laudantium","saepe"]},{"id":2,"name":"Qui officia inventore et.","description":"Ut eveniet a aut dolorem reiciendis. Vitae quibusdam nisi esse voluptas. Minima veniam deserunt beatae voluptatibus eum reprehenderit.","ean":"4656648527667","upc":"382397673789","image":"http:\/\/placeimg.com\/640\/480\/tech","images":[{"title":"Ut quaerat sequi enim est.","description":"Inventore possimus sint ipsum aut. Architecto excepturi quam et qui reiciendis. Fugit nesciunt doloribus rerum ipsa blanditiis pariatur natus.","url":"https:\/\/picsum.photos\/640\/480"},{"title":"Consequatur ab ut qui rerum.","description":"Est quae consequatur dolores expedita. Provident dicta corrupti provident qui et rerum. Voluptatum quasi omnis cupiditate vero mollitia ut dolor. Nulla doloribus veniam asperiores.","url":"https:\/\/picsum.photos\/640\/480"},{"title":"Ut odio dolore sed.","description":"Aspernatur deserunt nobis dolorum et accusantium. Ipsam minus sunt adipisci dolorem incidunt nostrum. Quisquam non deleniti a perferendis ut officia saepe. Consectetur sit ducimus error et illo.","url":"https:\/\/picsum.photos\/640\/480"}],"net_price":7.55,"taxes":22,"price":9.21,"categories":[72,73,74,75],"tags":["voluptatem"]}]}

=== api-evangelist/fakerapi/examples/fakerapi-list-books-example.json
{"status":"OK","code":200,"locale":"en_US","seed":"42","total":2,"data":[{"id":1,"title":"Mock Turtle in the.","author":"Gladyce Ortiz","genre":"Et","description":"Mock Turtle replied, counting off the fire, licking her paws and washing her face--and she is only a child!' The Queen turned crimson with fury, and, after folding his arms and frowning at the mouth.","isbn":"9797826980333","image":"http:\/\/placeimg.com\/480\/640\/any","published":"2003-10-05","publisher":"Optio Aut"},{"id":2,"title":"For some minutes.","author":"Vince Wintheiser","genre":"Voluptas","description":"King. (The jury all looked puzzled.) 'He must have imitated somebody else's hand,' said the Gryphon whispered in reply, 'for fear they should forget them before the trial's begun.' 'They're putting.","isbn":"9780998046761","image":"http:\/\/placeimg.com\/480\/640\/any","published":"1989-12-24","publisher":"Non Dolorum"}]}
